### Categorial variables
<pre>                       
                                               Categorical Variables
                                                Nominal        Ordinal
                                          (Red,Green,Blue)     (Low,Medium,High)
                                          (Male, Female)
                                            
</pre>
Kaggle link : https://www.kaggle.com/c/cat-in-the-dat-ii/data

In [1]:
import pandas as pd
from sklearn import preprocessing

In [2]:
df = pd.read_csv('../input/train_cat.csv')

In [3]:
df.head()

id  bin_0  bin_1  bin_2 bin_3 bin_4 nom_0      nom_1    nom_2       nom_3  \
0   0    0.0    0.0    0.0     F     N   Red  Trapezoid  Hamster      Russia   
1   1    1.0    1.0    0.0     F     Y   Red       Star  Axolotl         NaN   
2   2    0.0    1.0    0.0     F     N   Red        NaN  Hamster      Canada   
3   3    NaN    0.0    0.0     F     N   Red     Circle  Hamster     Finland   
4   4    0.0    NaN    0.0     T     N   Red   Triangle  Hamster  Costa Rica   

   ...      nom_9 ord_0        ord_1     ord_2 ord_3 ord_4  ord_5  day month  \
0  ...  02e7c8990   3.0  Contributor       Hot     c     U     Pw  6.0   3.0   
1  ...  f37df64af   3.0  Grandmaster      Warm     e     X     pE  7.0   7.0   
2  ...        NaN   3.0          NaN  Freezing     n     P     eN  5.0   9.0   
3  ...  f9d456e57   1.0       Novice  Lava Hot     a     C    NaN  3.0   3.0   
4  ...  c5361037c   3.0  Grandmaster      Cold     h     C     OZ  5.0  12.0   

  target  
0      0  
1      0  
2      0  
3      0  
4      0  

[5 rows x 25 columns]

In [4]:
df.bin_1.value_counts()

0.0    474018
1.0    107979
Name: bin_1, dtype: int64

In [5]:
df.bin_4.value_counts()

N    312344
Y    269609
Name: bin_4, dtype: int64

In [6]:
df.nom_0.value_counts()

Red      323286
Blue     205861
Green     52601
Name: nom_0, dtype: int64

In [7]:
df.ord_2.value_counts()

Freezing       142726
Warm           124239
Cold            97822
Boiling Hot     84790
Hot             67508
Lava Hot        64840
Name: ord_2, dtype: int64

In [8]:
df.day.value_counts()

3.0    113835
5.0    110464
6.0     97432
7.0     86435
1.0     84724
2.0     65495
4.0     23663
Name: day, dtype: int64

In [9]:
df.month.value_counts()

8.0     79245
3.0     70160
5.0     68906
12.0    68340
6.0     60478
7.0     53480
1.0     52154
11.0    51165
2.0     40700
9.0     20620
4.0     14614
10.0     2150
Name: month, dtype: int64

In [10]:
le  = preprocessing.LabelEncoder()

In [11]:
le.fit(df.bin_0.fillna(-1).values)

LabelEncoder()

In [12]:
le.classes_

array([-1.,  0.,  1.])

In [13]:
df.bin_0.values.tolist()

[0.0,
 1.0,
 0.0,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 nan,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0

In [14]:
le.transform(df.bin_0.fillna(-1).values)

array([1, 2, 1, ..., 1, 2, 1], dtype=int64)

In [15]:
df.dtypes.value_counts()

object     17
float64     6
int64       2
dtype: int64

In [16]:
binarize = preprocessing.LabelBinarizer()

In [17]:
binarize.fit_transform(df.bin_0.fillna(-1))

array([[0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       ...,
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [19]:
ohe = preprocessing.OneHotEncoder()

In [23]:
cat_feats = [c for c in df.columns if c not in ["id","target"]]
cat_feats

['bin_0',
 'bin_1',
 'bin_2',
 'bin_3',
 'bin_4',
 'nom_0',
 'nom_1',
 'nom_2',
 'nom_3',
 'nom_4',
 'nom_5',
 'nom_6',
 'nom_7',
 'nom_8',
 'nom_9',
 'ord_0',
 'ord_1',
 'ord_2',
 'ord_3',
 'ord_4',
 'ord_5',
 'day',
 'month']

In [26]:
df[cat_feats].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 23 columns):
bin_0    582106 non-null float64
bin_1    581997 non-null float64
bin_2    582070 non-null float64
bin_3    581986 non-null object
bin_4    581953 non-null object
nom_0    581748 non-null object
nom_1    581844 non-null object
nom_2    581965 non-null object
nom_3    581879 non-null object
nom_4    581965 non-null object
nom_5    582222 non-null object
nom_6    581869 non-null object
nom_7    581997 non-null object
nom_8    582245 non-null object
nom_9    581927 non-null object
ord_0    581712 non-null float64
ord_1    581959 non-null object
ord_2    581925 non-null object
ord_3    582084 non-null object
ord_4    582070 non-null object
ord_5    582287 non-null object
day      582048 non-null float64
month    582012 non-null float64
dtypes: float64(6), object(17)
memory usage: 105.3+ MB


In [27]:
for c in cat_feats:
    df[c] = df[c].astype(str)

In [28]:
ohe.fit(df[cat_feats].fillna("-1"))

OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)

In [29]:
ohe.transform(df[cat_feats].fillna("-1"))

<600000x5723 sparse matrix of type '<class 'numpy.float64'>'
	with 13800000 stored elements in Compressed Sparse Row format>